### ISSUE TITLE
Add Plug-In API

### ISSUE THREAD

**Issue by qinwf** [vnijs/radiant#10]
Is there any possibility to add more GUI component to the Radiant with some code or loading packages.

For example, [Rcmdr: Extending the R Commander by “Plug-In” Packages](http://www.r-project.org/doc/Rnews/Rnews_2007-3.pdf).

**Comment by vnijs** [comment]
I will create docs and an example of how you can add components. In the meantime, you need a file with an analysis, a summary, and a plot function (see R/, e.g., [single_mean.R](https://github.com/vnijs/radiant/blob/master/R/single_mean.R)). Then you need a file that generates the ui for the tool (e.g., [single_mean_ui.R](https://github.com/vnijs/radiant/blob/master/inst/quant/tools/analysis/single_mean_ui.R)) and then you add a line to the overall app ui-file (e.g., [ui.R](https://github.com/vnijs/radiant/blob/master/inst/quant/tools/analysis/single_mean_ui.R)).

You can also source chunks of one app into another (see [here](https://github.com/vnijs/radiant#source-code)).

**Comment by vnijs** [comment]
@picarus I like this idea. I will try to put an example together in the next couple of weeks.

FYI my hope is that extensions could be housed at the repos linked below. That way they will be organized and improvements can be more easily shared across projects.

https://github.com/radiant-rstats

**Comment by vnijs** [comment]
That took a bit longer than planned :)

Radiant development has been moved to https://github.com/radiant-rstats. Updated documentation is available at https://radiant-rstats.github.io/docs/. The new structure of the app should make it easier to extend the app with new menus. Take a look at https://github.com/radiant-rstats/radiant.design as an example of how to extend Radiant

As soon as the development versions of Shiny and DT hit CRAN I'll push the new Radiant packages as well

Please open any new issues at https://github.com/radiant-rstats/radiant/issues
