### ISSUE TITLE
Problem with filter-functionality

### ISSUE THREAD

**Issue by Woosah** [vnijs/radiant#12]
I waited a bit to post this until I checked on multiple browsers and multiple systems, but I cannot get the filter-cuntion to work.

 Everytime, I check the box to apply a filter (anywhere within the marketing instance, either on the "pure" r-side nor on the "batch"-side with "win_launcher()") the field for entering the condition is displayed, but nothing within it is actually applied to the data. And I mean really nothing! 

I am no experienced programmer nor did I have the time to dig into the potential source of this but I hope that this blunt description may help a little.

Tested systems: W7 64bit, one with all admin rights, one with totally restricted rights. Everywhere, all functions worked but the filter.

Browsers: Firefix 37.0.2, Chrome 42.0.2311.135 and IE11 (newest version)

Maybe I am just not seeing the obvious, but I don't know....

**Comment by vnijs** [comment]
The help file (use the ? icon on the Data > View page or  http://vnijs.github.io/radiant/base/view.html) states:

"Type your statement in the Filter box and press CTRL-return (or CMD-return on mac) to see the result on screen or an error below the box if the expression is invalid."

Does that work for you? If not, what version of Radiant do you have installed? Use:
```r
packageVersion('radiant') 
```

**Comment by Woosah** [comment]
Oh this embarrassment...oh my god...read the documentation more carefully, stupid! ;-)

**Comment by Woosah** [comment]
Really really great package (to add this a little late)!

**Comment by vnijs** [comment]
No worries @Woosah. Happens for everyone now and then :) I have thought about adding a button to the filter field. Does take up space though. Will think about it some more.

If you like the package feel free to 'star' it on Github :)

**Comment by Woosah** [comment]
Done!
