### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by vnijs** [vnijs/radiant#13]
- Gather and Spread in Data > Transform
- Poisson (with offset option)
- Marginals for probit
- Conjoint market simulation and estimation for multiple respondents
- etc.

**Comment by vnijs** [comment]
Done: 
- Change Data > Merge to Data > Combine and add intersect(), union(), setdiff(), bind_rows() and bind_cols()

**Comment by haughp** [comment]
Any plans to branch out into forecasting (ETS, ARIMA, NNETAR etc) and Arules (Association rules mining). 

Great work BTW...

**Comment by vnijs** [comment]
@haughp I do intend to create additional modules/app that build on the base functionality in Radiant. ETS/Forecasting is one but Customer/Predictive Analytics is a higher priority because I'll be teaching a course in this space (relatively) soon. The issue is finding time to implement new features :) 

Just curious ... What are you be interested in using this for? A class? If so, what is the class?

**Comment by haughp** [comment]
hi,  I would like to build out a platform for use at a production level.
Radiant has allot of features I would like to integrate into the platform.
Forecasting and association rules analysis is something I would like to
build in also. I haven't had a deep dive under the hood of radiant,
hopefully this is something I can add.

**Comment by vnijs** [comment]
Interesting. Can you expand on what you mean by 'at a production level'? Just in case it is relevant for you ... Radiant has a strong copy-left / open source license.

**Comment by haughp** [comment]
We would like to build out a production level business analytic s platform,
This is for internal business use only!!

The approach you have taken with radiant is something of interest and
something we would like to investigate further.

Is this something that you believe would be in violation of the licence?

**Comment by vnijs** [comment]
Good question. There is no problem using the tool internally. You can even modify the code for internal use. See the link below about the GPL license which is similar to the AGPL license I have for Radiant. For any use outside the organization you would need to open-source the code.

Of course I hope that you would contribute improvements and extensions where possible. My hope/plan is to use https://github.com/radiant-rstats for this purpose. Here different projects could work from a common base and then customize for different areas/tools as needed. 

I'd be happy to take more about this through email (radiant@rady.ucsd.edu).

http://stackoverflow.com/a/1492956/1974918

**Comment by vnijs** [comment]
Radiant development has been moved to https://github.com/radiant-rstats. Updated documentation is available at https://radiant-rstats.github.io/docs/

As soon as the development versions of Shiny and DT hit CRAN I'll push the new Radiant packages as well

Please open any new issues at https://github.com/radiant-rstats/radiant/issues
