### ISSUE TITLE
strip archives from git history

### ISSUE THREAD

**Issue by jimhester** [vnijs/radiant#14]
Cloning this repository is very painful because of the previous Mini-Cran inclusion.

I would suggest you use the [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to clean the repo history of all archive files.

The following reduced the radiant directory size from over 700M to 61M on my machine.

```bash
alias bfg=java -jar bfg-1.12.3.jar
bfg -D '*.{gz,tgz,zip}' radiant
cd radiant && git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

**Comment by vnijs** [comment]
Thanks Jim! Worked. Everything seems to work but now travis is complaining about the repos (see below). Any idea what might be going on?

Using worker: worker-linux-08b40318-1.bb.travis-ci.org:travis-linux-6
system_info
Build system information
Build language: r
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"
0.58s$ git clone --depth=50 --branch=master git://github.com/vnijs/radiant.git vnijs/radiant
Cloning into 'vnijs/radiant'...
remote: Counting objects: 1288, done.
remote: Compressing objects: 100% (730/730), done.
remote: Total 1288 (delta 695), reused 949 (delta 524), pack-reused 0
Receiving objects: 100% (1288/1288), 8.62 MiB | 0 bytes/s, done.
Resolving deltas: 100% (695/695), done.
Checking connectivity... done.
$ cd vnijs/radiant
$ git checkout -qf a1f13596571576000ac4f04333e7353cdfcff2a9
fatal: reference is not a tree: a1f13596571576000ac4f04333e7353cdfcff2a9
The command "git checkout -qf a1f13596571576000ac4f04333e7353cdfcff2a9" failed and exited with 128 during .
Your build has been stopped.
