### ISSUE TITLE
manage Panel : error with S4Vectors package

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#20]
Hi Vincent,
I have not changed anything since one month in manage.R file. But today I got this error
I'am using S4Vectors 0.6.1. 
The same error is also in tranform panel.
Any suggestion?
Thanks
Karim

error in evaluating the argument 'x' in selecting a method for function 'slice': Error in .Call2("Rle_constructor", values, lengths, check, 0L, PACKAGE = "S4Vectors") : 
  Rle of type 'list' is not supported

**Comment by vnijs** [comment]
I have no idea what S4Vectors is and how you are are using it. It is not a part of Radiant at all so I have no idea what is going on. The only lead is that `slice` is a function in the dplyr package. Presumably you are trying to pass in an object that is not a list or a data.frame. Try transforming the object first.

**Comment by kmezhoud** [comment]
The object is Diamonds datasets...
Thanks

**Comment by vnijs** [comment]
Presumably you do something to that data with S4vectors before it goes to the transform or manage panel. Try to replicate the error in a simpler setting where you use your S4... function and then call one functions exported by Radiant (e.g., radiant::getdata).

**Comment by kmezhoud** [comment]
Hi Vincent,
The problem comes when I attach IRanges package (http://bioconductor.org/packages/release/bioc/html/IRanges.html). 
There is some dplyr functions that are masked.
How can I avoid this masks? 
Thanks

Attaching package: ‘IRanges’
The following objects are masked from ‘package:dplyr’:
    collapse, desc, slice
The following object is masked from ‘package:tidyr’:
    expand
The following object is masked from ‘package:lubridate’:
    %within%
The following object is masked from ‘package:psych’:
    reflect

**Comment by kmezhoud** [comment]
I modified in radiant.R file 
142      dplyr::slice(1:min(nshow,n)) %>%

It resolve the display of tables in manage and transform panels. 
It remains the summary of transform panel...
