### ISSUE TITLE
Radiant will not execute correctly: MathJax issue

### ISSUE THREAD

**Issue by studentdave** [vnijs/radiant#21]
Error when trying to run Radiant:
I see this in the browser (chrome)
ERROR: path[1]="/www/MathJax/": No such file or directory

i see this on the command line
> radiant("marketing")

Listening on http://127.0.0.1:7160
Error in normalizePath(directoryPath, mustWork = TRUE) : 
  path[1]="/www/MathJax/": No such file or directory
Error in normalizePath(directoryPath, mustWork = TRUE) : 
  path[1]="/www/MathJax/": No such file or directory

Info:
RStudio
Version 0.99.465 – © 2009-2015 RStudio, Inc.

> R.Version()
$platform
[1] "x86_64-apple-darwin13.4.0"

$arch
[1] "x86_64"

$os
[1] "darwin13.4.0"

$system
[1] "x86_64, darwin13.4.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "2.1"

$year
[1] "2015"

$month
[1] "06"

$day
[1] "18"

$`svn rev`
[1] "68531"

$language
[1] "R"

$version.string
[1] "R version 3.2.1 (2015-06-18)"

$nickname
[1] "World-Famous Astronaut"

> packageVersion("radiant")
[1] ‘0.1.83’

**Comment by vnijs** [comment]
I don't see this error when I install and run the version of Radiant on CRAN. However, if you are using R 3.2 you are better off with the latest version. Try the command below. You may need to do a "Session > Restart R". 

install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")

**Comment by studentdave** [comment]
i restarted and installed as you have shown.  here's my seemingly new error

> radiant(app="marketing")
Loading required package: shiny

Attaching package: ‘shiny’

The following object is masked _by_ ‘.GlobalEnv’:

    withMathJax


Listening on http://127.0.0.1:4343
Error in normalizePath(directoryPath, mustWork = TRUE) : 
  path[1]="/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MathJaxR/www/MathJax/": No such file or directory
Error in normalizePath(directoryPath, mustWork = TRUE) : 
  path[1]="/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MathJaxR/www/MathJax/": No such file or directory

**Comment by studentdave** [comment]
after reseting everything a bunch of times, it seems i got it to work! :) thank you for your support.

**Comment by vnijs** [comment]
Glad to here that @studentdave. It is often easier to restart R or even just restart Rstudio before installing. Just an R quirk.
