### ISSUE TITLE
Error in installation from GitHub

### ISSUE THREAD

**Issue by mdlama** [vnijs/radiant#23]
I'm attempting to install Radiant from GitHub using devtools.  I'm getting the following error, however:

    ** preparing package for lazy loading
    Error : object ‘print.arrange’ is not exported by 'namespace:gridExtra'
    ERROR: lazy loading failed for package ‘radiant’

I'm using R 3.2.1.  Thanks!

- Drew

**Comment by vnijs** [comment]
Hi Drew. A new version of the package gridExtra was just released. Which breaks a few thing. I working on it and hope to have the update ready later today. In the mean time could you try to install using the command below? 

install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")

You may need to first run the command below so you **don't** use version 2.0.0 of gridExtra:

`remove.packages('gridExtra')`

**Comment by vnijs** [comment]
@mdlama Looks like everything is now working fine with the new version of gridExtra. Could you try installing using the command below?

`install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")`

to run Radiant use:

`radiant()`

**Comment by mdlama** [comment]
Awesome, thanks, Vincent.  Works like a charm now.

- Drew

**Comment by vnijs** [comment]
Glad to hear it Drew. I'll close this issue. If you have other comments please let me know.

**Comment by sco-lo-digital** [comment]
Hi, I'm getting this error when calling
radiant::radiant("analytics") 
Error: object ‘print.arrange’ is not exported by 'namespace:gridExtra'

I have gridExtra 2.0.0. Do I need to remove it? What packages depend on it?

**Comment by vnijs** [comment]
Hi Scott,

Did you follow the install instructions at
http://vnijs.github.io/radiant/install.html ?

Vincent

**Comment by sco-lo-digital** [comment]
Hi Vincent,

Thanks for the reply. Yes, I did follow the install instructions at that location.

I tried updating packages as well, but no luck there either. Any other suggestions?

Best
Scott

**Comment by vnijs** [comment]
I can't replicate the issue you are having Scott. Do you get any messages
when you enter the commands below? Did you try creating a launcher using
radiant::launcher('analytics') as suggested in the install instructions? If
so, any messages?

library(radiant)
radiant("analytics")
