### ISSUE TITLE
Error: could not find function "nmissing" in Explore tab

### ISSUE THREAD

**Issue by ax42** [vnijs/radiant#26]
I get the message above when clicking on the Explore tab in the diamond dataset.  I am running Radiant within a shiny server (inst/base) directory using a checked-out version of the master branch.  My shiny server logfile shows:

```
Listening on http://127.0.0.1:60101
Error in eval(substitute(expr), envir, enclos) :
  could not find function "nmissing"
Error: could not find function "nmissing"
Execution halted
```

The logfile shows all packages loading correctly.  Any help would be appreciated.

**Comment by vnijs** [comment]
@ax42 Can you tell me the version number from the DESCRIPTION file? Also, to make sure you have all the same packages installed, please run the command below on the server:

```r
install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")
```

**Comment by vnijs** [comment]
Latest versions on github run fine on shinyapps so should run on any shiny-server install as well. See example below.

https://internal.shinyapps.io/vnijs/base/?SSUID=6c912b3284

**Comment by ax42** [comment]
running the install.packages above gives an error:
``` 
Warning: dependencies ‘DT’, ‘data.tree’ are not available

......

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  namespace ‘data.tree’ 0.1.6 is being loaded, but >= 0.1.7 is required
```

DESCRIPTION
```
Package: radiant
Title: Business Analytics using R and Shiny
Version: 0.2.67
Date: 2015-8-4
Authors@R: person("Vincent", "Nijs", , "radiant@rady.ucsd.edu", c("aut", "cre"))
```

**Comment by vnijs** [comment]
@ax42 thanks for the report. I have had some interesting problems with shiny, dplyr, and Rcpp. I believe these are resolved now.

I just uploaded version 0.2.72. Note that you may be asked to install Rcpp 0.12.0. Just follow the instructions if that happens. Best to refresh/restart R before installing with:

install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")

Let me know if you have any problems.

**Comment by ax42** [comment]
Thanks - works now.
