### ISSUE TITLE
X11 connection rejected because of wrong authentication.

### ISSUE THREAD

**Issue by ax42** [vnijs/radiant#27]
Just pulled the latest master, and get the error above when executing runApp() inside inst/base.  This seems to stop radiant from executing entirely.  I have run the 
```install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")``` command already.

I've seen this type of error before when some library needs tk -- is there a new dependency?

**Comment by vnijs** [comment]
Strange. If Shiny is already as 0.12.2 then perhaps it is related to data.tree. Can you build that packages directly from github?

https://github.com/gluc/data.tree

**Comment by vnijs** [comment]
Oh. And make sure Rcpp is at 0.12.0 or higher. You may need to check and update that manually. This is actually more likely to be the culprit because there is a check in the code that stops the app if 0.12.0 is not installed.

**Comment by vnijs** [comment]
I assume this is resolved in the latest version. If now please post a new issue.
