### ISSUE TITLE
R CMD check fails with dev version of tidyr

### ISSUE THREAD

**Issue by hadley** [vnijs/radiant#28]
```
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: plot.cross_tabs
> ### Title: Plot method for the cross_tabs function
> ### Aliases: plot.cross_tabs
> 
> ### ** Examples
> 
> result <- cross_tabs("newspaper", "Income", "Newspaper")
> plot(result, ct_check = c("observed","expected","chi_sq"))
Error in gather_.data.frame(., "variable", "values") : 
  argument "gather_cols" is missing, with no default
Calls: plot ... _fseq -> freduce -> withVisible -> <Anonymous> -> sshhr
Execution halted
```

Any ideas?

**Comment by vnijs** [comment]
@hadley Thanks for checking how changes to tidyr will affect others! Really appreciated.

The `tab` below used to gather fine but doesn't with the new tidyr. For 4/5 cases I switched to as.data.frame as that seems simpler and gives me what I need (and is not likely to change any time soon :)). 

More interesting, perhaps, is the segfault I ran into (see second block below).

```r
tab <- structure(c(39.1067931038135, 63.5264195668282, 32.4450680955929, 
52.704884372479), class = "table", .Dim = c(2L, 2L), .Dimnames = structure(list(
    c("Low Income", "High Income"), c("WS Journal", "USA Today"
    )), .Names = c("", "")))

tab %>%	data.frame(., check.names = FALSE)
```
I had been using `gather_` and as I was trying to figure out what was going on and trying to drop a variable I got  segfault in R-gui on mac (3.2.2) running the code below:

```r
tab <- structure(c(162.787931034483, 100.212068965517, 196.212068965517, 
120.787931034483), .Dim = c(2L, 2L), .Dimnames = structure(list(
    c("Low Income", "High Income"), c("WS Journal", "USA Today"
    )), .Names = c("", "")))

tab %>% 
  data.frame(., check.names = FALSE) %>%
  mutate(rnames = rownames(.)) %>% 
  gather_(., "variable", "values", -which(colnames(.) == "rnames"))
```

**Comment by hadley** [comment]
This works:

```R
tab %>% 
  gather(variable, values, -rnames)
```

so I think something is wrong with your column spec, and tidyr isn't doing a good job of warning. Let me look more

**Comment by hadley** [comment]
Ok, now I get: `Error: Unknown column names: -3`. 

You need:

```R
tab %>% 
  data.frame(., check.names = FALSE) %>%
  mutate(rnames = rownames(.)) %>% 
  gather_(., "variable", "values", setdiff(colnames(.), "rnames")))
```

**Comment by vnijs** [comment]
Hadn't thought about `setdiff`. Nice. Could a `setdiff` example perhaps be added to the documentation for `gather_`? Similarly, something like the below would be a nice add-on for the `dplyr::select_` documentation. Thanks @hadley 

```r
select_(iris, .dots = setdiff(colnames(iris), c("Petal.Length", "Petal.Width")))
```
