### ISSUE TITLE
Save decision tree as svg/png file

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#30]
Hi,
In actual version we can save dtree as pdf or ps using ```actionLink ``` function. 
If I am right, dtree plot uses ```mermaid``` library from ```DiagrammeR``` package and It is **not** the same process to save diagrammeR plot compared the standard plots that use ```plot_downloader``` function (as in Visualize panel).
It is not yet clear for me, how ```plot_downloader```  captures  ```plot_name``` from current plot. If it is possible to have simple example.

Any suggestion to use ```plot_downloader``` with DiagrammeR ```mermaid``` or ```grViz``` plots?
Thanks
Karim

**Comment by vnijs** [comment]
Don't have an answer for this one. I'm not sure it is possible to download svg plots or include them in knitr documents at this time. You can include them if you use rmarkdown but that doesn't help much in a shiny app. A couple of relevant discussions:

https://github.com/rich-iannone/DiagrammeR/issues/70

https://github.com/yihui/knitr/issues/754

**Comment by kmezhoud** [comment]
@vnijs Thank You.

**Comment by vnijs** [comment]
Link to review:

http://stackoverflow.com/questions/31645528/knit-dtdatatable-without-pandoc/31797947#31797947

Others:

http://blog.dominodatalab.com/interactive-dashboards-with-knitr-and-html-widgets/

http://stackoverflow.com/questions/21729415/generate-dynamic-r-markdown-blocks/33222656#33222656

http://stackoverflow.com/questions/33212428/automatically-saving-interactive-graph-in-r-to-a-specified-location-as-a-html-f/33212516#33212516

http://stackoverflow.com/questions/28585238/r-rendering-html-widget-in-external-browser

https://support.rstudio.com/hc/communities/public/questions/202578368-Rendering-HTML-widget-in-external-browser

**Comment by kmezhoud** [comment]
Hi @vnijs,
 thank you for all links. They are useful. I can now save diagrams as html. not bad.
server.R
```
output$Save_diagrammeR_plot <- downloadHandler(
  filename = function() {
    paste(getwd(),"DiagrammeRplot.html", sep="/")
  },
  content = function(file) {
    saveWidget(  
DiagrammeR::grViz("
    digraph{
      BRCA1  -> IFI16   [arrowhead = normal, color= LightGray, alpha=30, penwidth= 0.2] ;
      BRCA1  ->   NBN [arrowhead = normal] ;
      BRCA1  ->  TP53   [color= LightGray] ;
      IFI16  ->  TP53 [arrowtail = normal] ;
      PML  ->  TP53 [arrowtail = normal]
  },
  engine = neato,   #dot, neato|twopi|circo|
  width = 1200
"), file)
  }

 # browseURL(paste('file://',getwd(),"Reactomeplot.html", sep="/"))
  ## wait 1 sd before delete
  # p1 <- proc.time()
  # Sys.sleep(1)
  # proc.time() - p1
## delete file
  #,unlink(paste(getwd(),"DiagrammeRplot.html", sep="/"))
)
```
ui.R

```
downloadButton('Save_diagrammeR_plot', 'HTML')
```

**Comment by vnijs** [comment]
Hi @ramnathv

Here are some links i mentioned

**Comment by vnijs** [comment]
You could try https://github.com/rich-iannone/DiagrammeRsvg for convert a DiagrammeR plot to pdf or png. It requires V8 however and I don't want to add that dependency at this time. I added a function to the report feature so you can include diagrammer plots when you save the report to HTML. Looks like it will take some time before there is a convenient solution for this problem so I'll close this issue for now. Unless @ramnathv has suggestions?

https://github.com/vnijs/radiant/blob/master/inst/base/tools/app/report.R#L131-L177
