### ISSUE TITLE
Error starting https://internal.shinyapps.io/vnijs/quant/

### ISSUE THREAD

**Issue by ojessen** [vnijs/radiant#32]
The shiny app on shinyapps.io does not start, but throws the following error:

Error in function_list[[k]](value) : could not find function "sshhr"
Calls: local ... eval -> _fseq -> freduce -> withVisible -> <Anonymous>
Execution halted

**Comment by kmezhoud** [comment]
Hi,
I got this error. it disappeared without changing anything.
this function is defined in radiant.R file. 
https://github.com/vnijs/radiant/blob/ce43cb40f11679d3d74af835be84decfb3ae323e/R/radiant.R
```
sshhr <- function(...) suppressWarnings( suppressMessages( ... ) )
```
restart Rsession and clean your Global env. 
karim

**Comment by vnijs** [comment]
Thanks for letting me know @ojessen. Fixed now.
