### ISSUE TITLE
exists(r_data[['MyDataset']], envir=.GlobalEnv)

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#33]
Hi,
how can I check programmatically  if my new object exists or not under r_data.

I tested:
```
 exists('Mydatase', envir=.GlobalEnv)
 exists(r_data[['Mydatase']], envir=.GlobalEnv)
not_available('Mydatase')
```
Thanks

**Comment by vnijs** [comment]
`is.null(r_data$Mydatase)` should work. You will also want to add an entry to r_data$datasetlist else it won't show up in the data dropdown

**Comment by kmezhoud** [comment]
Thanks. That works.
