### ISSUE TITLE
add column with a factor: transform > create

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#34]
Hi Dr Vincent,
I would like to combine data frames. Before that, I need to add a column for every df with a class.
for example I would like to add new column named 'Origin' :
diamonds$Origin = 'Africa' (all rows have 'Africa')
I used Transform > create but I can't add a character/factor as variable.
```
diamonds$Origin = 'Africa'
Origin = rep('Africa',nrow(diamonds)
Origin = rep(’Africa’,3000)

```
How to? 
Thanks

**Comment by vnijs** [comment]
Just "Origin = 'Africa'" works for me. It will also generate the command you would need for the R > Report feature (i.e., `r_data[["diamonds"]] <- mutate(r_data[["diamonds"]], Origin = 'Africa')`)

**Comment by kmezhoud** [comment]
Does not work with my fork and works with last radiant.
```
**  **
The create command was not valid. The command entered was:

Origin == ‘Africa’

The error message was:

error in evaluating the argument 'args' in selecting a method for function 'do.call': Error in parse(text = cmd) : <text>:1:10: unexpected input
1: Origin == <e2>
             ^

Please try again. Examples are shown in the help file
** **
```
terminal
```
Warning in strsplit(msg, "\n") :
  input string 1 is invalid in this locale

```

**Comment by kmezhoud** [comment]
and numeric change works with my fork.

x = y - z

**Comment by kmezhoud** [comment]
That does not work within Rstudio. 
When I get the error I reopen the app (with the same session) in Firefox and than that works.
I can't test radiant within Rstudio.

**Comment by vnijs** [comment]
I'm not sure what you mean by 'within Rstudio'. The issue seems to be the quotes you are using around Africa. These should be simple ' marks and not ’. Furthermore, you are **assigning** a value to a variable when you use create so you should use = and not ==. You can only use == for logical comparisons.

**Comment by kmezhoud** [comment]
"within Rstudio "means runApp in Windows or launch.browser =FALSE.
That works in firefox with simple and double quotes.

**Comment by vnijs** [comment]
Please send a screen shot showing exactly when an issue occurs



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by kmezhoud** [comment]
The first screenshot shows the error using my fork in Rstudio
![error_Rstudio](https://drive.google.com/open?id=0B9NOY9eukkEeb1lpX29OZU9DNVk)
https://drive.google.com/open?id=0B9NOY9eukkEeb1lpX29OZU9DNVk

After I cliced on open in browser and reenter the same code : Origin = 'Africa' and thene taht works.

![No_error_Firefox](https://drive.google.com/open?id=0B9NOY9eukkEeamdYTFprbWo0a3M)
https://drive.google.com/open?id=0B9NOY9eukkEeamdYTFprbWo0a3M

Thanks

**Comment by vnijs** [comment]
As I already explained, you cannot use a 'curly' quote. If that is the default quote when you type something into Rstudio's browser there is nothing I can do about that. The 'curly' quote is a non-ascii character that R doesn't recognize.
