### ISSUE TITLE
replace blank with NA

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#35]
Hi Dr Vincent,
Transform > Remove missing value delete row with at less one blank. 
If I have some missing value in different lines I expect to loose a lot of data.
How can I replace blank by NA
```
df[df==""]  <- NA
```
Thanks

**Comment by vnijs** [comment]
See `recode` in the helpfile. For example:

"" = NA 

Documentation: http://vnijs.github.io/radiant/base/transform.html
