### ISSUE TITLE
Base > Probability Calculator > Uniform distribution : Std Dev

### ISSUE THREAD

**Issue by ajarvashisth** [vnijs/radiant#36]
The probability calculator function for Uniform dist  in file **radiant/R/prob_calc.R**  , line 958 has a typo
```R
stdev <- (max-min)^2 / 12  
```
should be 
```R
stdev <- (max-min)^2 / sqrt(12)
```

**Comment by vnijs** [comment]
Thanks. It should actually be:

`stdev <- sqrt((max-min)^2 / 12)`
