### ISSUE TITLE
error message showed up when initially double-check radiant.bat(marketing)

### ISSUE THREAD

**Issue by to6c** [vnijs/radiant#37]
After I installed the radiant and clicked the radiant.bat(marketing) , the cmd windows showed the message as follows:
Listening on http://127.0.0.1:4444
Error in eval(substitute(expr), envir, enclos) :
  corrupt 'grouped_df', contains 70 rows, and 168 rows in groups
Error in eval(substitute(expr), envir, enclos) :
  corrupt 'grouped_df', contains 70 rows, and 168 rows in groups
Error in eval(substitute(expr), envir, enclos) :
  corrupt 'grouped_df', contains 70 rows, and 168 rows in groups

**Comment by vnijs** [comment]
Can you provide some more information? What OS? What browser? Does a browser open? If so, what does it show? Did it work before? What version are you using? 

![image](https://cloud.githubusercontent.com/assets/2998956/10837076/825436ca-7e72-11e5-870c-26a9340827cf.png)

**Comment by to6c** [comment]
windows 10, chrome (opened) , R Studio was also running (Version 0.99.484).  R version 3.2.2 (2015-08-14) . Chrome showed the same error message too. But now I double checked the bat file and the browser will not show Radiant. This is first time I installed Radiant in this computer ( I have been using Studio for  two months).

**Comment by to6c** [comment]
I closed the cmd windows and ran the bat file again, now Radiant showed on the browser but with same error.

Listening on http://127.0.0.1:4444
Error in eval(substitute(expr), envir, enclos) :
  corrupt 'grouped_df', contains 70 rows, and 168 rows in groups

**Comment by vnijs** [comment]
I have over 300 students running Radiant this quarter but don't think I have seen this issue. Could you try the install instructions (exactly) linked below? Windows 10 can have permission issues with R packages when installed in c:\program files\ and packages in Documents folder. Any initial problems with Windows 10 were resolved by installing R in c:\R\R3.2.2 instead. 

http://vnijs.github.io/radiant/install

**Comment by vnijs** [comment]
Also, can you send a screen shot with ALL message lines from the terminal window? Thanks

**Comment by to6c** [comment]
I did follow the installation guide on http://vnijs.github.io/radiant/install. Here are ALL the messages lines from the terminal:

C:\Users\jason li\Desktop>"C:\R\R-32~1.2\bin\x64\R.exe" -e "if (!require(radiant)) { install.packages('radiant', repos = 'http://vnijs.github.io/radiant_miniCRAN/', type = 'binary') }; library(radiant); shiny::runApp(system.file('marketing', package='radiant'), port = 4444, launch.browser = TRUE)"

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> if (!require(radiant)) { install.packages('radiant', repos = 'http://vnijs.github.io/radiant_miniCRAN/', type = 'binary') }; library(radiant); shiny::runApp(system.file('marketing', package='radiant'), port = 4444, launch.browser = TRUE)
Loading required package: radiant
Loading required package: magrittr
Loading required package: ggplot2
Loading required package: lubridate
Loading required package: tidyr

Attaching package: 'tidyr'

The following object is masked from 'package:magrittr':

    extract

Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:lubridate':

    intersect, setdiff, union

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Attaching package: 'radiant'

The following object is masked from 'package:dplyr':

    mutate_each

The following object is masked from 'package:ggplot2':

    diamonds

Loading required package: shiny
Warning in dir.create("~/r_sessions") :
  'C:\Users\jason li\Documents\r_sessions' already exists

Listening on http://127.0.0.1:4444
Error in eval(substitute(expr), envir, enclos) :
  corrupt 'grouped_df', contains 70 rows, and 168 rows in groups

**Comment by vnijs** [comment]
Can you try updating to the latest version and removing the C:\Users\jason li\Documents\r_sessions directory? Like I said, I haven't seen this error before and cannot replicate it. Have you tried running Radiant on another computer?

**Comment by to6c** [comment]
Thank you Professor Vnijs,

I removed C:\Users\jason li\Documents\r_sessions directory and it worked fine now. Thanks.

**Comment by vnijs** [comment]
Excellent. Thanks for letting me know. It is best to stop Radiant by clicking the 'power' icon and then 'stop'. Otherwise it will try to open a backup next time you start Radiant. To clear out backups click 'power' and then 'refresh', or remove the `r_sessions` directory.
