### ISSUE TITLE
Geom_line color

### ISSUE THREAD

**Issue by DGrv** [vnijs/radiant#39]
First, thanks a lot for this great tool offering a great GUI for non R user.

I began to test it few days ago and I realized that the visualize function was not really behaving how I would have like or how ggplot2 is.

Here an example with the diamonds dataset :

```{r fig.width=7, fig.height=3.5}
visualize(dataset = "diamonds", xvar = "clarity", yvar = "carat", type = "line", color = "color")
```

![visualize 1](https://cloud.githubusercontent.com/assets/15691063/11000482/584d4bd8-84a2-11e5-946d-376f6fd20ea1.png)

If I then modify just a bit the visualize function to have the same behavior than ggplot2:

![visualize](https://cloud.githubusercontent.com/assets/15691063/11000495/6eed5f22-84a2-11e5-9ac6-51ec3d26557f.png)

I would really appreciate to have such possibility with radiant. I may not understand all the potential problem that my modification would do but I ask you to consider it :)

Here the changes : 

    else if (type == "line") {
        itt <- 1
        for (i in xvar) {
            for (j in yvar) {
                if (color == "none") {
                  if (is.factor(dat[[i]])) {
                    tbv <- if (is.null(byvar)) 
                      i
                    else c(i, byvar)
                    tmp <- dat %>% group_by_(.dots = tbv) %>% 
                      select_(j) %>% summarise_each(funs(mean))
                    plot_list[[itt]] <- ggplot(tmp, aes_string(x = i, 
                      y = j)) + geom_point() + geom_line(aes(group = 1))
                  }
                  else {
                    plot_list[[itt]] <- ggplot(dat, aes_string(x = i, 
                      y = j)) + geom_line()
                  }
                }
                else {
                  if (is.factor(dat[[i]])) {
                    tbv <- if (is.null(byvar)) 
                      i
                    else c(i, byvar)
                    print(tbv)
                    tmp <- dat %>% group_by_(.dots = tbv) %>% 
                      select_(j, color) %>% summarise_each(funs(mean))
Original code:
```{r}
                    plot_list[[itt]] <- ggplot(tmp, aes_string(x = i, 
                      y = j, color = color)) + geom_point() + 
                      geom_line(aes(group = 1))
```
New code:
```{r}
                    plot_list[[itt]] <- ggplot(tmp, aes_string(x = i, 
                      y = j, color = color, group=color)) + geom_point() + 
                      geom_line()
```
                  }
                  else {
Original code : 
```{r}
                    plot_list[[itt]] <- ggplot(dat, aes_string(x = i, 
                      y = j, color = color)) + geom_line()
```
New code:
```{r}
                    plot_list[[itt]] <- ggplot(dat, aes_string(x = i, 
                      y = j, color = color, group=color)) + geom_line()
```
                  }
                }

                if ("log_x" %in% axes) 
                  plot_list[[itt]] <- plot_list[[itt]] + xlab(paste("log", 
                    i))
                if ("log_y" %in% axes) 
                  plot_list[[itt]] <- plot_list[[itt]] + ylab(paste("log", 
                    j))
                itt <- itt + 1
            }
        }
    }

**Comment by vnijs** [comment]
Thanks @DGrv! Updated on Github. I will update the package versions at `radiant_miniCRAN` this weekend

**Comment by vnijs** [comment]
`color` should work correctly now in the latest version (0.3.70). Please try it out and let me know if there are any remaining issues.

`install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = 'binary')`

**Comment by DGrv** [comment]
I tried yesterday and it was working how expected.
Thanks a lot for the reactivity :)

**Comment by vnijs** [comment]
Glad to hear that. Thanks for identifying the issue and suggesting a fix



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu
