### ISSUE TITLE
lost the sync of my fork

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#40]
Hi,
I lost my sync fork when I changed the name of my repository.
I added a new upstream

```
git remote add upstream https://github.com/vnijs/radiant.git
git fetch upstream
```
The second command replaced my fork by radiant and I can't merge master/upstream

```
git merge upstream/master
```
Is there a way to compare and merge again my fork with radiant?
Thanks

**Comment by vnijs** [comment]
Don't know. You will have to do some searches on git and github for this situation I think

**Comment by kmezhoud** [comment]
Hi,
To re-sync again a fork, we need to
```
git remote add upstream https://github.com/vnijs/radiant.git
git fetch upstream
git checkout master
git merge upstream/master
```
and then resolve conflicts manually file by file .

**Comment by vnijs** [comment]
Sound like a good amount of work. Thanks for posting the update
