### ISSUE TITLE
Decision Tree: Issue with cost

### ISSUE THREAD

**Issue by ezriah** [vnijs/radiant#41]
First, thanks for creating such a great tool. The problem I'm running into with decision trees is that the costs from previous branches don't seem to be inherited at all. Also the terminal payoff doesn't seem to be taking cost into account. I see that you may have created a fix for this but it doesn't seem to be implemented. 

- Alyssa

**Comment by ezriah** [comment]
Here's the decision tree I'm working on. The later nodes don't inherit the
cost:

Name: Survey
type: decision
Survey:
  cost: 30
  type: chance
  Unfavorable:
    p: .7
    payoff: 0
    type: decision
    Drill:
      cost: 100
      type: chance
      oil:
        p: .143
        payoff: 800
      dry:
        p: .857
        payoff: 0
    Sell:
        payoff: 90
  Favorable:
    p: .3
    payoff: 0
    type: decision
    Drill:
      cost: 100
      type: chance
      oil:
        p: .5
        payoff: 800
      dry:
        p: .5
        payoff: 0
    Sell:
        payoff: 90
NoSurvey:
  type: decision
  Drill:
    cost: 100
    type: chance
    oil:
      p: .25
      payoff: 800
    dry:
      p: .75
      payoff: 0
  Sell:
    payoff: 90

**Comment by ezriah** [comment]
In this example, the payoff for hiring an agent with a cost of 1000 and a
payoff of 2000 should ultimately result in a payoff of 1000 (2000-1000).

**Comment by vnijs** [comment]
That is not how it works (i.e., later nodes do indeed not 'inherit' cost). Rather, the cost is taken into account appropriately when you fold back the tree. I think it would be confusing if you put in a payoff for a terminal of say, 2000, but the tree shows 1000. That said, it would be nice to see where a cost is deducted. There are something in-the-works that will address that. 

In sum, the tree is correct. It is just not displayed as had you expected. In fact, I have not seen tools that display output as you suggest. If you have seen such examples please let me know.

**Comment by ezriah** [comment]
My operations research textbook (Introduction to Operations Research by
Hillier and Lieberman) teaches it that way. They use the same example but
perform analysis with Analytics Solver Platform, an Excel plugin, which
gives the results in the terminal nodes as the payoff minus the cumulative
costs. Thanks for such a quick response. Let me know if you'd like more
details.

**Comment by vnijs** [comment]
Unfortunately I don't have the book and don't know the plugin. I expect the plugin does not, however, automatically update the payoff for the terminal nodes. I assume the user provides the final payoff, adjusted for cost. If that is not a correct assumption could you perhaps send me the xls file and I'll look up the plugin.
