### ISSUE TITLE
Package ‘radiant’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#42]
Hi Vincent,
https://cran.r-project.org/web/packages/radiant/index.html
Karim

**Comment by vnijs** [comment]
I know. I'm not happy about it but I can't easy update radiant on CRAN until DT and shinyAce are updated on CRAN.

**Comment by kmezhoud** [comment]
Hi,
If in description file you set actual versions
 DT (>=0.1),
 shinyAce (>=0.1) 
rather than
shinyAce (>= 0.2.1),
DT (>= 0.1.39),

radiant loses some functionalities?

**Comment by vnijs** [comment]
Yes it does. There are various issues in DT and a few in shinyAce.

**Comment by kmezhoud** [comment]
Hi Dr Vincent,
Any new about the next CRAN release and radiant?
Karim

**Comment by vnijs** [comment]
Working on it

**Comment by vnijs** [comment]
@kmezhoud Radiant is not back on CRAN yet but I expect it to be soon (i.e., a few weeks). Still waiting for an update to shiny and DT. To get an idea of the extension structure I have been working on take a look at the repo's linked at the organization below. radiant.example has radiant.base as a dependencies and you can add applications, help, etc. to that base app. i.e., radiant.base is be the package I intend to submit to CRAN. When I have time I'll plan to submit my own extensions (e.g., quant, marketing, analytics) as separate packages.

https://github.com/radiant-rstats

**Comment by kmezhoud** [comment]
Thank you for information
great radiant metamorphose.
congratulation

**Comment by vnijs** [comment]
Radiant development has been moved to https://github.com/radiant-rstats. Updated documentation is available at https://radiant-rstats.github.io/docs/

As soon as the development versions of Shiny and DT hit CRAN I'll push the new Radiant packages as well

Please open any new issues at https://github.com/radiant-rstats/radiant/issues
