### ISSUE TITLE
avoid  MathJaxR dependency

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#43]
Dear Dr Vincent,
To avoid github depends, I have to bundle MathJaxR to my radiantFork.
I copied
``` 
MathJaxR/inst/MathJax to radiantFork/inst/MathJax
```
```
MathJax/R/withMathJax.R to radiantFork/R/withMathJax.R
```
I changed the two global.R files :
```
if (r_local) {
  addResourcePath("MathJax", file.path(system.file(package = "radiantFork"), "MathJax/"))
  withMathJax <- radiantFork::withMathJaxR
}

```

and I removed MathJaxR depends from description files and imports from /R files.
There isn't 
```
importFrom(MathJaxR withMathJaxR)
```
in namespace. but there is 
```
export(withMathJax)
```
When I build my radiantFork, I have always the Warning message of the MathJaxR depends

```
* checking for file bioCancer/DESCRIPTION ... OK
* preparing bioCancer:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package bioCancer ...
** R
** data
*** moving datasets to lazyload DB
Warning: namespace MathJaxR is not available and has been replaced
by .GlobalEnv when processing object withMathJax
Loading required package: DBI
```
I removed  radiantFork/build folder. 
I removed dependencies.R file.
I searched for all files in package that have 'MathJaxR' string using bash/regex. 
I removed .Rdata and Rhistory hidden files

Only withMathJax.R and global.R have 'withMathJax' string.

please, have you an idea from where the dependency of MathJaxR always exists?
Thanks

**Comment by vnijs** [comment]
I'll look into it. In the meantime, you can have users use the following command.

install.packages("withMathJax", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = 'binary')

**Comment by kmezhoud** [comment]
```
 install.packages("withMathJax", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = 'binary')
Warning in install.packages :
  URL 'http://vnijs.github.io/radiant_miniCRAN/bin/macosx/mavericks/contrib/3.3/PACKAGES.gz': status was '404 Not Found'
Warning in install.packages :
  URL 'http://vnijs.github.io/radiant_miniCRAN/bin/macosx/mavericks/contrib/3.3/PACKAGES': status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://vnijs.github.io/radiant_miniCRAN/bin/macosx/mavericks/contrib/3.3:
  cannot download all files
Warning in install.packages :
  package ‘withMathJax’ is not available (as a binary package for R Under development)
```
sessionInfo
```
R Under development (unstable) (2016-01-06 r69875)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

```

**Comment by vnijs** [comment]
Sorry ...

install.packages("MathJaxR", repos = "http://vnijs.github.io/radiant_miniCRAN/")

**Comment by kmezhoud** [comment]
Yes,
What is the difference with
```
install_github("vnijs/MathJaxR")
```
which works too.

My goal is to include/ bundle MathJaxR into my radiantFork. 
I can't submit package with github depends :)
Thanks

**Comment by kmezhoud** [comment]
I have a RData session in /data folder that calls an old withMathJax function from MathJaxR package. 
So I need just to remove withMathJax function from RData session in /data folder.
Thanks

**Comment by vnijs** [comment]
@kmezhoud I'm sorry to say that you cannot submit the version of kmezhoud/bioCancer on Github to CRAN. A very large chunk of the code and help files are a direct copy-and-paste from Radiant. You are violating the licenses for code and documentation in several ways. e.g., you cannot simply add your name to a copy-righted help file. 

Unfortunately, there is not a good extension mechanism for Radiant at the moment. I'm working on that and hope to have something ready to try-out in a couple of weeks.

**Comment by kmezhoud** [comment]
@vnijs How can use the code of radiant without violating licenses. 
I am expecting to submit bioCancer to Bioconductor.
I will remove my name in all doc/help of radiant.

**Comment by vnijs** [comment]
Like I said, it is not just the helpfiles but also the code. I'm afraid you
will have to be a bit patient until I get an extension mechanism setup.

**Comment by kmezhoud** [comment]
Ok
I am waiting.
Good job.
