### ISSUE TITLE
Chi- Squared distribution Mean

### ISSUE THREAD

**Issue by ajarvashisth** [vnijs/radiant#44]
While exploring the chi-squared distribution i stumbled across that radiant displays the mean of chi squared distribution as   DOF (degrees of freedom) +1,    where as it should be   DOF +2.  The graph however shows the mean and mode correctly .

**Comment by vnijs** [comment]
Thanks. The mean should actually be equal to the DOF. Where did you see DOF + 2?

**Comment by ajarvashisth** [comment]
Hello .. Sorry for my typo .by "mean" I meant the mode or the highest point in the graph.  You are right mean = DOF and mode =   DOF -2

**Comment by vnijs** [comment]
No problem Ajar. Thanks
