### ISSUE TITLE
Add URL param that would cause the session to NOT be saved

### ISSUE THREAD

**Issue by daattali** [vnijs/radiant#45]
I saw @vnijs share a link to a radiant session that was part of a bug report.  I clicked the link, moved to a different tab, and now the original link goes to my new tab.

It could be useful if the URL was `...?SSUID=blahblahblah&update=0` which would tell radiant to just bring me to the same point as that session, but not record any further actions.

**Comment by vnijs** [comment]
Thanks for the suggestion @daattali. The link below is 'fixed' so if you make changes another user visiting the same link will not see the changes

http://vnijs.rady.ucsd.edu:3838/analytics/?fixed&SSUID=7d3e155083
