### ISSUE TITLE
trouble loading radiant

### ISSUE THREAD

**Issue by subhashjaini** [vnijs/radiant#46]
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘nlme’ 3.1-122 is already loaded, but >= 3.1.123 is required
In addition: Warning message:
package ‘radiant’ was built under R version 3.2.4 
Error: package or namespace load failed for ‘radiant’

I downloaded nlme and it still isnt working.. got any ideas as to why?

Thanks!

Btw, good job!

**Comment by subhashjaini** [comment]
nm, i had to manually type in install.packages and it worked fine! :)

**Comment by vnijs** [comment]
I assume you tried installing Radiant from github using devtools. If so, you have to manage dependencies yourself. If you install Radiant using the command below and then update to the latest using `devtools::install_github("vnijs/radiant")`

`install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = "binary")`

**Comment by subhashjaini** [comment]
That was it!! Thanks man! :)
