### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by subhashjaini** [vnijs/radiant#47]
not really an issue, but a neat logo or some sort of branding would be nice for this thing :)

I am refering to it in my school presentation for my masters and all I have to go by is "Radiant"... I might put a picture of a diamon or something :)

**Comment by vnijs** [comment]
Good point :) I use the slides in the ppt linked below to introduce Radiant. The green-sun image on slide 9 will have to do for a logo for now.

https://www.dropbox.com/s/gggkqizv6p4x6f4/radiant-intro.ppt?dl=0

Would you mind sharing your presentation whey you are done? If you are interested, below a few recent videos I posted about Radiant. 

https://www.youtube.com/watch?v=-ji0NyQrx7w
https://www.youtube.com/watch?v=kwuOzuX-tjM
https://www.youtube.com/watch?v=XLR9cquIMAg
https://www.youtube.com/watch?v=vi_EBuFQUVE
https://www.youtube.com/watch?v=vTovTggb4do

**Comment by vnijs** [comment]
Not sure if relevant for you here but: feather files may be a nice way do move data between R and Python

http://blog.rstudio.org/2016/03/29/feather/

**Comment by subhashjaini** [comment]
This is great!! I will definitely keep an eye on the project!!!  I am
currently using sql lite, but I am always down with higher performance
(especially with this sensor data).

calling python in r or vice versa generally is no good, and I love how
feather acknowledges that and tries to address shortening the gap between r
and python files!

**Comment by vnijs** [comment]
Radiant development has been moved to https://github.com/radiant-rstats. Updated documentation is available at https://radiant-rstats.github.io/docs/

As soon as the development versions of Shiny and DT hit CRAN I'll push the new Radiant packages as well

Please open any new issues at https://github.com/radiant-rstats/radiant/issues
