### ISSUE TITLE
Dropdown variable list doesnt showup in the Visualize option

### ISSUE THREAD

**Issue by LakshmiNittala** [vnijs/radiant#48]
When I pick the Visualize option to start plotting I dont see the dropdown list of variables. I can see then in the view and other options though. I have the latest version of Radiant, Rstudio and R.
-Lakshmi

**Comment by vnijs** [comment]
I can't reproduce the issue. The variables shown depend on the plot type selected and the type of variables. Can you post a screen shot and the data (by email)?
