### ISSUE TITLE
make my bar graphs have manually selected colors

### ISSUE THREAD

**Issue by subhashjaini** [vnijs/radiant#49]
anyway to do that?

```{r fig.width=10.5, fig.height=5.25, dpi = 72}
visualize(dataset = "W", xvar = "NumberOfPeople", yvar = "Sentiment", bins = 4, alpha = 0.54, data_filter = "Belong", custom = TRUE)+
theme(axis.text = element_text(size = 24)

)
```

I tried col, color, colour as a regular paramters, according tothe function, it should just be color...

any thoughts?

**Comment by vnijs** [comment]
Do you mean something like the following?

```r
visualize(dataset = "diamonds", xvar = "cut", yvar = "price", type = "bar", custom = TRUE) + 
geom_bar(stat="identity", colour="red", fill = "orange") 
```

In ggplot2, a bar-chart uses `fill` in to specify a specific variable to plot/color _by_. For example:

```r
visualize(dataset = "diamonds", xvar = "cut", yvar = "price", type = "bar", fill = "clarity", custom = FALSE)
```

Winston's cookbook has some nice examples:

http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/

**Comment by subhashjaini** [comment]
Ooops, I was dealing with a histogram,

**Comment by vnijs** [comment]
You can **add** pretty much anything to a plot generated using `visualize` that you want. However, I'm not sure if it is possible to **edit** a geom that has already been specified in ggplot2. I'll have to think about that a bit more. One issue is that `color` is also a parameter for line and scatter plots that has a different meaning than you are looking for. Anyway, you are not restricted to using only the functions exported by radiant. You can still fall back on regular ggplot commands. For example:

```r
ggplot(r_data[["W"]], aes(x = NumberOfPeople)) + 
geom_histogram(fill = "blue")
```
