### ISSUE TITLE
r 3.4

### ISSUE THREAD

**Issue by subhashjaini** [vnijs/radiant#50]
how can i get radiant for 3.4?  When I try to install radiant on my ubuntu server, I get this message

package ‘radiant’ is not available (for R version 3.2.4 Revised)

**Comment by vnijs** [comment]
For a linux server remove `type = 'binary'` and make sure to specify the correct repo (see below) . It should install from source and the latest version of Radiant is available. Note that you cannot `knit` reports on a server as this would be a security risk.

`install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")`

**Comment by subhashjaini** [comment]
I tried this 

sudo su - -c "R -e \"install.packages('radiant', repos='http://vnijs.github.io/radiant_miniCRAN/')\""

It tells me the same when I run the install.packages (in r)

Warning messages:
1: In install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/") :
  installation of package ‘rsvg’ had non-zero exit status
2: In install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/") :
  installation of package ‘DiagrammeR’ had non-zero exit status
3: In install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/") :
  installation of package ‘radiant’ had non-zero exit status

**Comment by vnijs** [comment]
On linux `rsvg` may require you to install a system utility first. Try the following and then see what it needs:

`install.packages("rsvg", repos = "http://vnijs.github.io/radiant_miniCRAN/")`

**Comment by subhashjaini** [comment]
gibberish to me, but maybe this rings a bell to you...?

> install.packages('rsvg', repos='http://vnijs.github.io/radiant_miniCRAN/')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL '
http://vnijs.github.io/radiant_miniCRAN/src/contrib/rsvg_0.4.tar.gz'
Content type 'application/octet-stream' length 7857 bytes
==================================================
downloaded 7857 bytes

* installing *source* package ‘rsvg’ ...
** package ‘rsvg’ successfully unpacked and MD5 sums checked
Package librsvg-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `librsvg-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librsvg-2.0' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lrsvg
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because librsvg-2.0 was not found. Try installing:
 * deb: librsvg2-dev (Debian, Ubuntu, etc)
 * rpm: librsvg2-devel (Fedora, EPEL)
 * csw: librsvg_dev, sunx11_devel (Solaris)
 * brew: librsvg (OSX)
If librsvg-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a librsvg-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘rsvg’
* removing ‘/usr/local/lib/R/site-library/rsvg’

The downloaded source packages are in
        ‘/tmp/RtmpQJaxCh/downloaded_packages’
Warning message:
In install.packages("rsvg", repos = "
http://vnijs.github.io/radiant_miniCRAN/") :
  installation of package ‘rsvg’ had non-zero exit status

**Comment by vnijs** [comment]
The utility it needs is shown in the message as suggested.

"No package 'librsvg-2.0' found"

If you are using Ubuntu you would need something like

`sudo apt-get install librsvg2-bin`

**Comment by subhashjaini** [comment]
sudo apt-get install librsvg2-bin

ran... but now i tried the rsvg again and had no luck

**Comment by subhashjaini** [comment]
I am trying 
sudo apt-get install librsvg2-dev

since thts what the error recomended

**Comment by subhashjaini** [comment]
awesome!! that unlocked it and let me download radiant on ubuntu!! Later int he summer when im bored, ill write a how-to on radiant inside digital ocean! :)

**Comment by subhashjaini** [comment]
Thanks again!! :)

Overall, all I needed to do was this... 

sudo apt-get install librsvg2-bin
sudo su - -c "R -e \"install.packages('rsvg', repos='http://vnijs.github.io/radiant_miniCRAN/')\""
sudo su - -c "R -e \"install.packages('radiant', repos='http://vnijs.github.io/radiant_miniCRAN/')\""

and I was good!!!

**Comment by vnijs** [comment]
Glad that worked. Good to have this a (closed) issue in case others run into the same thing.

**Comment by RSchwinn** [comment]
I ran into issues installing radiant on an under-powered ubuntu server. The problem was that R on ubuntu requires that dependencies be compiled locally from the R source code (downloaded from cran) but compiling sometimes required more than the 1GB RAM on my system. The work around is to install the packages from precompiled binaries as follows:

    sudo apt-get update     # refresh
    sudo apt-get install software-properties-common
    sudo add-apt-repository -y "ppa:marutter/rrutter"
    sudo add-apt-repository -y "ppa:marutter/c2d4u"
    sudo apt-get update     # now with new repos
    sudo apt-get install r-cran-readr # now replace readr with the names of the dependencies that previously failed to install.

Notice that this may be risky because these files were not officially compiled/distributed by cran. Hope this can help someone else facing this issue!

**Comment by vnijs** [comment]
@RSchwinn I forgot that ubuntu offers binaries for (some) R-packages. Thanks for sharing. 

FYI Radiant development moved to https://github.com/radiant-rstats a while back. Install instructions are available at: https://radiant-rstats.github.io/docs/install.html

**Comment by subhashjaini** [comment]
Hey man!! You still around?

**Comment by vnijs** [comment]
FYI Radiant development moved to https://github.com/radiant-rstats a while back. Install instructions are available at: https://radiant-rstats.github.io/docs/install.html

**Comment by subhashjaini** [comment]
Can you help me move environment variables across sessions? I'll pay a
little

**Comment by vnijs** [comment]
Please clarify what you mean @subhashjaini. Example?

**Comment by subhashjaini** [comment]
Sure! I have a production job that runs in sql server 2016. It starts a new
session, then loads a file, then runs.  If I can keep a session on in my
server machine, and a tool can access it, it'd be great

**Comment by subhashjaini** [comment]
Sjaini@Precizion.io

**Comment by vnijs** [comment]
I *think* you are asking about running Radiant inside sqlserver. If so ... I have never done anything like that. If that is not what you are after, please provide (a lot) more detail.

**Comment by subhashjaini** [comment]
Radiant allows you to pull variables from multiple r sessions, I want that
aspect of radiant

Can you help with that?

Ignore the fact that this is sql server....can you help me get a variable
from one session to another through memory?

**Comment by vnijs** [comment]
Sorry. No idea what you mean by "r session" here :) 

Are you trying to access data from the global environment or from a database? You can use Data > Manage to access data in the global environment. If you want data from a database, use Report > Rmd and specify the connection information. Then "register" the data.frame so you can access it from the dropdown menu's (https://radiant-rstats.github.io/radiant.data/reference/register.html)

**Comment by subhashjaini** [comment]
I want to access data from one live r session to another like your app
does. The global environment seems to be fit that session, not the machine

**Comment by vnijs** [comment]
Radiant uses the shiny package to communicate between an R process and the browser. There is no communication between different R sessions. Maybe shiny is something you could use or else perhaps https://github.com/r-lib/callr
