### ISSUE TITLE
Download button doesn't work properly

### ISSUE THREAD

**Issue by janeoeyre** [vnijs/radiant#51]
When click the download button on View page, it gives the error "slice condition does not evaluate to an integer or numeric vector. " Other download buttons have similar issues.

**Comment by vnijs** [comment]
I don't see this issue on Windows or Mac. Can you provide a reproducible example? Does this happen with a specific dataset you are using?

**Comment by vnijs** [comment]
Without a reproducible example there is not much I can do. I can't see the problem in the current-version on Github. Did you follow the install instructions here? I'll close this for now but feel free to reopen if you have more information
