### ISSUE TITLE
Regression - Center Option

### ISSUE THREAD

**Issue by koushr89** [vnijs/radiant#54]
Hi Vincent,

I don't understand why in Radiant when the "center" option is used for linear regression, the estimated intercept is 0. Using the Diamonds dataset, when I use the transform tab to meancenter the independent variables, the estimated intercept is different than 0 (see image below).
![image](https://user-images.githubusercontent.com/54371813/65159462-1f370500-da02-11e9-891e-88101be5a375.png)
I am guessing that the "center" option also meancenters the DV. In that case, the explanation on website should change to reflect that:
![image](https://user-images.githubusercontent.com/54371813/65159733-8a80d700-da02-11e9-834c-604b0ec45f3c.png)

If possible, could you update the "center" option so that it only centers the explanatory variables? Or perhaps add a new option. 

Thanks

**Comment by vnijs** [comment]
You are correct that centering also mean-centers the DV. This is an extension of sorts of the "standardize" option that also affects both the IVs and DVs. Fixing the docs will be easy to do. Would that work for you?

**Comment by koushr89** [comment]
Thank you Vincent,
I would prefer to have the "center" option that does not meancenter the DV but I understand if you prefer not to do that. In that case correcting the docs would be good :)

**Comment by vnijs** [comment]
You should see the updated documentation at https://radiant-rstats.github.io/docs/model/regress.html in a few minutes. I'll leave this issue open for a while in case I get around to it but ... I doubt I'll be able to change this any time soon given other priorities I have at the moment

**Comment by vnijs** [comment]
FYI Development moved to the radiant-rstats organization on github some time ago. If you have other issues please post there

https://github.com/radiant-rstats/radiant/issues
