### ISSUE TITLE
Training Variable: same seed, different outputs

### ISSUE THREAD

**Issue by koushr89** [vnijs/radiant#55]
Hi again Vincent,

Sorry to bother you again. I was trying to teach validation analysis to my students, and although all students set the seed to a specific value (111), students got two different results on different computers. I thought it was related to Windows vs. MacOS or 32bits vs. 64bits but these two factors were not the issue. 

It would be great if you can check this to see what might be the issue. Last year when I ran the same analysis, all 170+ students got similar results. 

Best
Koushyar

**Comment by vnijs** [comment]
@koushr89 Can you post more information at https://github.com/radiant-rstats/radiant/issues? A reproducible example showing exactly what you were trying to do would be very helpful

**Comment by mnstat** [comment]
Hi Vincent,
How can I run your nice app in my R?
Tnx

**Comment by vnijs** [comment]
Radiant is developed @ https://github.com/radiant-rstats
Install instructions: https://radiant-rstats.github.io/docs/install.html
