### ISSUE TITLE
How to set directory for load the data?

### ISSUE THREAD

**Issue by MackyKavinsky** [vnijs/radiant#57]
Let's say i am a user, how can i set the directory into a folder with the dataset? So it will be easier for me to just select the dataset instead of needing to browse for the files. @vnijs 

![image](https://user-images.githubusercontent.com/34124958/115495251-d8725680-a299-11eb-920f-6cac0d5285f3.png)

**Comment by vnijs** [comment]
Use Rstudio projects before you start Radiant. Radiant will pick this up and make accessing data in your projects quick and easy. See the section on Rstudio projects on the site linked below

https://r4ds.had.co.nz/workflow-projects.html

**Comment by vnijs** [comment]
Closing for now

**Comment by MackyKavinsky** [comment]
is there are a way that I can change inside the code? And if it is possible how should I change?
![image](https://user-images.githubusercontent.com/34124958/116177681-d4857f00-a746-11eb-99e1-2b56ff10cbfa.png)

**Comment by vnijs** [comment]
You can set something like the below in your .Rprofile file

`options(radiant.sf_volumes=c(Some_directory = "C:/Users/me/Dropbox/"))`
